on:
  schedule:
    - cron: "*/5 * * * *"
  # push:
  #   branches:
  #     - 'master'

name: CRON Trigger
jobs:
  trigger:
    name: Ubuntu runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - name: Execute script
        run: npm start
      - name: Run github
        run: |
          git config user.name hackerhgl
          git config user.email hackerhgl@gmail.com
          git add .
          git commit -m "Script triggered by automated runner"
          git push origin master
